ERROR_ON = 'Line %d, Column %d: '
WRONG_SIGNATURE = 'Method "%s" already defined in "%s" with a different signature.'
SELF_IS_READONLY = 'Variable "self" is read-only.'
LOCAL_ALREADY_DEFINED = 'Variable "%s" is already defined in method "%s".'
INCOMPATIBLE_TYPES = 'Cannot convert "%s" into "%s".'
VARIABLE_NOT_DEFINED = 'Variable "%s" is not defined in "%s".'
INVALID_OPERATION = 'Operation is not defined between "%s" and "%s".'
CYCLIC_INHERITANCE = 'Type "%s" is included in a cyclic inheritance.'

INFERENCE_ON = 'Ln %d, Col %d: '
INF_ATTR = 'On class "%s", attribute "%s": type "%s"'
INF_PARAM = 'On method "%s" of class "%s", param "%s": type "%s"'
INF_RETRN = 'Return of method "%s" in class "%s", type "%s"'
INF_VAR = 'Varible "%s", type "%s"'
